shim-version: v0.3.12@sha256:b81f2295ae6750d61e94f810ce24077360001b6ec795d13643f3170df29e304d
cvm-version: 0.6.7
cpus: 16
memory: 65536

containers:
  - name: "memex"
    image: "us-central1-docker.pkg.dev/workshop-labs-pbc/pollux-docker/cpu@sha256:ed20fd0db13fc23105c2b2582f24b55cc8b06cab71263fa9ecb51dfa9d98ad32"
    entrypoint: ["python", "-m", "src.memex.main", "--prod", "--port", "8001"]
    env:
      - KEY_MODE: "real_keys"
      - LOG_LEVEL: "INFO"
      - EMBEDDING_SERVER_URL: "https://confidential-pollux-embeddings.debug.wsl.containers.tinfoil.dev"
    secrets:
      - DATABASE_URL
      - TINFOIL_API_KEY
      - EXA_API_KEY
      - INTERNAL_SERVICE_SECRET

shim:
  listen-port: 443
  upstream-port: 8001
  publish-attestation: true
  tls-challenge: dns
  paths:
    - /ping
    - /set_dek
    - /v1/context/*
    - /v1/personalize/*
    - /v1/user/*
